package org.bb.main.gui;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

import javax.swing.JOptionPane;

import org.bb.database.DBFunctions;
import org.bb.main.Main;
import org.bb.util.Event;
import org.bb.util.CHAP;
import org.bb.util.SavedPreferences;

public class LoginPanel extends javax.swing.JPanel{
  
  private static volatile LoginPanel instance = null;
  public Buttons buttons;
  Main main;
  public static String lastNameUser;
  public static LoginPanel getInstance(){
    return instance;
    
  }
  
  public LoginPanel(Buttons btns, Main main){
	  this.main = main;
    instance = this;
    setOpaque(false);
    initComponents();
    buttons = btns;
    if(main.sp.isLogged){
    	lblWelcome.setForeground(Color.white);
    	lblWelcome.setText("Bem vindo, "+ main.sp.usrname +"!");
    	btnSignout.setText("Desconectar");
    	loadLogoutScreen();
    	buttons.activeButtons();
    } else {
    	loadLoginScreen();
    }
    txtNickname.selectAll();
    
    txtPassword.addKeyListener(new KeyAdapter()     
    {
      @Override
      public void keyPressed(KeyEvent ke)
      {
        if(ke.getKeyCode() == KeyEvent.VK_ENTER)
          btnLoginActionPerformed(null);
      }
    });
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    lblNickname = new javax.swing.JLabel();
    txtNickname = new javax.swing.JTextField();
    btnLogin = new javax.swing.JButton();
    btnSignup = new javax.swing.JButton();
    txtPassword = new javax.swing.JPasswordField();
    lblPassword = new javax.swing.JLabel();
    txtServer = new javax.swing.JTextField();
    lblServer = new javax.swing.JLabel();
    
    lblWelcome = new javax.swing.JLabel();
    btnSignout = new javax.swing.JButton();

    btnSignout.addActionListener(new ActionListener() {
		@Override
		public void actionPerformed(ActionEvent arg0) {
			buttons.desactiveButtons();
			main.sp.isLogged = false;
			loadLoginScreen();
		}
	});
    setNextFocusableComponent(txtNickname);

    lblNickname.setForeground(java.awt.Color.white);
    lblNickname.setText("Nome de Usuário:");

    txtNickname.setText(lastNameUser);

    btnLogin.setText("Login");
    btnLogin.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnLoginActionPerformed(evt);
      }
    });

    btnSignup.setText("Cadastre-se");
    btnSignup.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnClearActionPerformed(evt);
      }
    });

    lblPassword.setForeground(java.awt.Color.white);
    lblPassword.setText("Senha:");

    lblServer.setForeground(new java.awt.Color(255, 255, 255));
    lblServer.setText("Servidor:");

//    loadLoginScreen();
  }// </editor-fold>//GEN-END:initComponents

  private void loadLoginScreen(){
	  this.removeAll();
	  org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
	    this.setLayout(layout);
	    layout.setHorizontalGroup(
	      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
	      .add(layout.createSequentialGroup()
	        .addContainerGap()
	        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
	          .add(layout.createSequentialGroup()
	            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
	              .add(lblNickname)
	              .add(lblPassword))
	            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
	            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
	              .add(txtNickname, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
	              .add(txtPassword, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)))
	          .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
	            .add(btnSignup)
	            .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
	            .add(btnLogin)))
	        .addContainerGap())
	    );
	    layout.setVerticalGroup(
	      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
	      .add(layout.createSequentialGroup()
	        .addContainerGap()
	        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
	          .add(lblNickname)
	          .add(txtNickname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
	        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
	        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
	          .add(txtPassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
	          .add(lblPassword))
	        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
	        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE))
	        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 13, Short.MAX_VALUE)
	        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
	          .add(btnLogin)
	          .add(btnSignup))
	        .addContainerGap())
	    );
  }
  
  private void loadLogoutScreen(){
	  this.removeAll();
	  org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
	    this.setLayout(layout);
	    layout.setHorizontalGroup(
	      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
	      .add(layout.createSequentialGroup()
	        .addContainerGap()
	        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
	          .add(layout.createSequentialGroup()
	            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
	              .add(lblWelcome))
	            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
	            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
	              .add(btnSignout))))
	        .addContainerGap())
	    );
	    layout.setVerticalGroup(
	      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
	      .add(layout.createSequentialGroup()
	        .addContainerGap()
	        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
	          .add(lblWelcome)
	          .add(btnSignout))
	        .addContainerGap())
	    );
  }
  
  private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
	  main.addCadastro();
  }//GEN-LAST:event_btnClearActionPerformed

  private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
    String nickname = this.txtNickname.getText();
    String pwd = new String ( this.txtPassword.getPassword());
    if (!nickname.equals("")){
    	if(DBFunctions.getUserDB(nickname, pwd, main)){
        	lblWelcome.setForeground(Color.white);
        	lblWelcome.setText("Bem vindo, "+nickname+"!");
        	btnSignout.setText("Desconectar");
        	main.sp.setUserLogged();
        	main.sp.updateSavedPreferences();
        	loadLogoutScreen();
        	buttons.activeButtons();
    	}
    }
  }
  
  public void setEnabledComponents(Boolean b){
	  btnSignup.setEnabled(b);
	  btnLogin.setEnabled(b);
	  lblNickname.setEnabled(b);
	  lblPassword.setEnabled(b);
	  lblServer.setEnabled(b);
	  txtNickname.setEnabled(b);
	  txtPassword.setEnabled(b);
	  txtServer.setEnabled(b);
	  lblWelcome.setEnabled(b);
	  btnSignout.setEnabled(b);
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnSignup;
  private javax.swing.JButton btnLogin;
  private javax.swing.JLabel lblNickname;
  private javax.swing.JLabel lblPassword;
  private javax.swing.JLabel lblServer;
  private javax.swing.JTextField txtNickname;
  private javax.swing.JPasswordField txtPassword;
  private javax.swing.JTextField txtServer;
  
  private javax.swing.JLabel lblWelcome;
  private javax.swing.JButton btnSignout;
  // End of variables declaration//GEN-END:variables
  
  /**
   * Paints the background
   * @param g
   */
  @Override
  public void paintComponent(Graphics g)
  {
    g.setColor(new Color(0, 0, 0, 150));
    g.fillRect(0, 0, getWidth(), getHeight());
  }
  
  public void continueLogin(long challenge)
  {
    String nickname = this.txtNickname.getText();
    String password = this.txtPassword.getText();
    long   hash     = CHAP.createChecksum(challenge, password);
      
    // The Client request a login
    //ClientThread.getInstance().Server.login2(new Event(new Object[]{nickname, hash}));
  }
}